# Generated by Django 5.1.3 on 2025-01-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
