# Generated by Django 5.1.3 on 2025-01-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_guardage_order_guardsex_order_guardstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oderID',
        ),
    ]
