# Generated by Django 5.1.3 on 2025-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_oderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guardStatus',
            field=models.CharField(blank=True, choices=[('ORDINARY', 'ORDINARY'), ('ADVANCED', 'ADVANCED')], max_length=10, null=True),
        ),
    ]
